---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 84.252.130.149
 #     ansible_user: root
#     ansible_ssh_pass: "Pa$$w0rd"
vector:
  hosts:
    vector-01:
      ansible_host: 51.250.67.210
 #     ansible_user: root
 #     ansible_ssh_pass: "Pa$$w0rd"
lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 51.250.69.250
 #     ansible_user: root
 #     ansible_ssh_pass: "Pa$$w0rd"